### ISSUE TITLE
(int) seq

### ISSUE THREAD

**Issue by dominictarr** [mikeal/SLEEP#1]
can this be less strict?

Not much is lost with a float as the timestamp - then you can use it to represent actual time,
(for example, with https://npmjs.org/package/monotonic-timestamp )

I think as long as it's a number, and is STRICTLY INCREASING.

You could go a bit further out, and relax this to the point that it's just a string that always sorts after previous strings. This could have some benefits because you could represent updates at a much finer granularity, and you'd never get a data format overflow apocalypse.

(hope that is not part of your retirement plan ;)

**Comment by mikeal** [comment]
hrm.... strings get in to strange string sorting issues about which is greater based on encoding. I also think that people are far more likely to screw up strings and accidentally have duplicate sequences (for instance, anyone using a timestamp that wasn't as smart as you and didn't write monotonic timestamp library)

but floats i think are good idea so long as we specify that only integers and floats greater than 0 are valid sequences. this way we get two features:
- everyone who request's since=0 is insured to get the full database history.
- people can _hide_ inserts in to their database from SLEEP by inserting them as negative integers in their sequence index

**Comment by mikeal** [comment]
fixed in the spec, nothing needs to change in the implementation cause JavaScript :)
